### ISSUE TITLE
Relative paths are not supported

### ISSUE THREAD

**Issue by pgrzywaczcic** [django-webpack/webpack-bundle-tracker#25] opened 2017-07-07 05:41 UTC
If you compile webpack bundles on one machine (like some CI) then deploy the application in production in a different directory, webpack-bundle-tracker can't read files. The reason for this is the bundles contains absolute paths, which may be different during runtime than when bundles were created.

This is a common case with CI environments and when target machines aren't powerful enough.

**Comment by Schnouki** [comment] 2017-09-19 13:25
Same here. However the workaround in #4 works for me.

**Comment by levic** [comment] 2017-11-24 03:26
Was looking at implementing options from #4, #10 & #25 

Extracting out the use cases:
- `path` to be removed entirely 
- `path` to be relative rather than absolute (to fix build on one machine and use on another)

Otions:
1. a `postChunkHook` option that gets called on each chunk before writing the results to disk
1. an array of `postChunkHooks`. The default array would only contain the functionality for [generating `publicPath`](https://github.com/ezhome/webpack-bundle-tracker/blob/9833d094a520ccfcea99011d1e7ade182ca98048/index.js#L88). Removing `path`, or making the path relative would hooks added to the list. An advantage of this is that you could apply multiple independent hooks. Compared to the first option, this is only a few lines of extra code but does add interface complexity without a clear use-case (no-one has yet shown a need for multiple modifications)

@owais Do you have a preference?

**Comment by owais** [comment] 2017-11-24 04:05
@levic I'm find with changing it so that `path` refers to the relative path instead of absolute path provided:

1. It does not break django-webpack-loader. Fix django-webpack-loader if it does. Bump major version.
2. It does not conflict with django-webpack-loader documentation. Fix docs if it does. Bump major version.
3. Support all possible cases such as `../../some_dir/bundles/bundle.js` 


But it raises some questions.

1. What should the path in relative to? The webpack config file? package.json file? That is not clear to me.
2. Should BundleTracker require another argument to specify the root to which the paths should be relative to?
3. Should it be required or optional? If optional, what should the plugin default to?

We'll need to prepare a major version release for webpack-bundle-tracker and if needed for django-webpack-loader as well. 

Happy to accept PRs but please discuss action plan first in case you find something is needs to be fixed django-webpack-loader.


/cc @n3ssi3 @alexhayes @darkowic

**Comment by darkowic** [comment] 2017-11-24 04:59
> What should the path in relative to? The webpack config file? package.json file? That is not clear to me.

```
const relativePathRoot = path.join(process.cwd(), 'dist', **path.sep); // the workaround from #4
```
In my case, I use a relative path to `dist` directory. Though, it should be fully configurable IMHO. Hmm, but in most cases, if someone wants to set relative path it will be probably app `src` directory.

> Should BundleTracker require another argument to specify the root to which the paths should be relative to?

Yes.

> Should it be required or optional? If optional, what should the plugin default to?

It should be optional. The default should behave like current implementation.


Basically, I think that this functionality should be optional by providing relative path

**Comment by owais** [comment] 2017-11-24 05:24
> Basically, I think that this functionality should be optional by providing relative path

You mean specifying the root path should be optional but path should always be present and should always be relative the the root path. I agree with that.

I'd like to add another constraint to make sure implementation is flexible:

4. If rootPath option is set to `/` then the resultant paths should essentially by absolute paths.

**Comment by owais** [comment] 2017-11-24 05:28
>> What should the path in relative to? The webpack config file? package.json file? That is not clear to me.

> In my case, I use a relative path to dist directory. Though, it should be fully configurable IMHO. Hmm, but in most cases, if someone wants to set relative path it will be probably app src directory.

I'm not sure about this. I think the default root should be webpack config's directory. If this does not make sense then I'd suggest to make it a required option.

**Comment by melck** [comment] 2018-03-17 16:47
I proposed a pr to resolve this issue in that following way : 
-  When path is defined in options and relative, chunk file path is relative to the resolved path. 

What do you think about that @owais  ?

(PS: Sorry for my poor english :))

**Comment by owais** [comment] 2018-03-18 14:01
Defined in webpack options or specifically in bundle tracker options?

**Comment by melck** [comment] 2018-03-19 08:28
@owais I use the option of plugin named `path` to determine whether his path is relative or absolute and then modify path of chunks when it's relative.

I read all solutions you proposed here. I think the plugin must stay simple and should always use relative path to tracking file. I'm not sure what to do to add some magics without adding complexity and breaking existing builds. I have fixed my personnal use case like that : 

```javascript
const path = require('path')
const each = require('lodash/fp/each')
const BundleTrackerPlugin = require('webpack-bundle-tracker')

// https://github.com/ezhome/webpack-bundle-tracker/issues/25
class RelativeBundleTrackerPlugin extends BundleTrackerPlugin {
  convertPathChunks(chunks){
    each(each(chunk => {
      chunk.path = path.relative(this.options.path, chunk.path)
    }))(chunks)
  }
  writeOutput(compiler, contents) {
    if (contents.status === 'done')  {
      this.convertPathChunks(contents.chunks)
    }

    super.writeOutput(compiler, contents)
  }
}

module.exports = RelativeBundleTrackerPlugin
```

**Comment by veryhappythings** [comment] 2018-05-11 09:28
I've found @melck's solution to work for me (I used the code from your branch, not the code here, for what it's worth - I believe the logic is the same) but I did find that it was a little unusual when your webpack-stats.json is not in the root of your app. I've currently got my stats file in the same directory as my bundles.

My settings ended up being: 
```new BundleTracker({path: '.', filename: "./path/to/webpack-stats.json"})```

Which resulted in a chunk that looked like `{"example":[{"name":"example.css","path":"example.css"}` in my stats file. This feels correct to me - the path to the bundle is right, relative to my stats file.

I found this quite a weird setup, though. I'd expect to configuration to look more like

```new BundleTracker({path: './path/to/', filename: "webpack-stats.json"})```

But due to the way chunk filenames hit this code, that gave me a stats file that looked like this: `{"example":[{"name":"example.css","path":"../../example.css"}`

So it looks like the path that we're working relative to here, for each chunk, is simply the filename, not the actual destination path of the chunk.

**Comment by melck** [comment] 2018-05-11 12:57
@veryhappythings It's maybe when publicPath is set. Could you give me a fictive path of stat file and publicPath option  on your 2 examples to better reproduce  ?

**Comment by veryhappythings** [comment] 2018-05-11 13:26
Sure thing! Here's what I've got, slightly anonymized. I'm not using publicPath in this setup.
```
module.exports = {
  mode: "production",
  entry: {
    first: [
      "./app/assets/js/index.js",
      "./app/assets/scss/first.scss",
    ],
    second: [
      "./app/assets/js/index.js",
      "./app/assets/scss/second.scss",
    ],

  output: {
    path: path.resolve('./app/static/bundles/'),
    filename: "[name].js",
  },
  plugins: [
    new MiniCssExtractPlugin(),
    new BundleTracker({path: '.', filename: "./app/static/bundles/webpack-stats.json"})
  ],
  module: {
    rules: [
      {
        // Load fonts from bootstrap
        test: /\.woff2?$|\.ttf$|\.eot$|\.svg$/,
        loader: "file-loader",
        options: {
            name: "[name].[ext]"
          }
      },
      {
        test: /\.scss$/,
        loader: [
          MiniCssExtractPlugin.loader,
          "css-loader?sourceMap",
          "sass-loader?sourceMap"
        ]
      }
    ]
  }
```

So it looks to me like chunk.path is giving me just the chunk name - `first.css` - the path of the file relative to my target output path.

**Comment by melck** [comment] 2018-05-11 19:48
@veryhappythings I have checked behavior of my pull request. You was totally right. It was not working as intended. I have fixed her.

@owais what do you think about this pull-request ? Do you need help on this project ?

**Comment by veryhappythings** [comment] 2018-05-14 11:59
Nice one, thanks! I'm a bit concerned that we don't have any tests for this and I'm not well versed enough in django-webpack-loader's code to know if this will work with it reliably. Maybe someone else can help on those fronts :)

I'm also wondering if this behaviour is getting a little too implicit - people have been using workarounds to get this working for a while, so perhaps we should just have an explicit flag to enable relative paths? I suppose there might be cases where you would want relative paths in your webpack config (which is typically checked into git and shared) but need absolute paths in your stats file (which might not be in git, and might be generated specifically for production).

**Comment by lcmartinezdev** [comment] 2019-06-23 05:54
@owais did you see this pr? https://github.com/owais/webpack-bundle-tracker/pull/29

I need that to compile my assets on my local instances and add to repo in order to avoid issues when it's compiling on production instances.

**Comment by owais** [comment] 2020-01-08 13:32
Fixed by https://github.com/owais/webpack-bundle-tracker/pull/29

**Closed as completed** 2020-01-08 13:32 UTC
